/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 corgi.gltf --transform 
Files: corgi.gltf [22.55MB] > corgi-transformed.glb [289.57KB] (99%)
Author: leijiaoshou (https://sketchfab.com/leijiaoshou)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/corgi-dog-7afb2c8ef92c40819abc690584e6772a
Title: corgi dog
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/corgi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['dog_mesh_22_Material_#25_0'].geometry} material={materials.Material_25} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/corgi-transformed.glb')
